### ISSUE TITLE
ArgumentCountError: Constructor in App\Models\Product Requires Arguments When None Provided by Eloquent Event

### ISSUE THREAD

**Issue by Disservin** [laravel/framework#51689]
### Laravel Version

11.9.2

### PHP Version

8.3.6

### Description

Since Laravel 10 (the following code worked fine with version 9), you will run into the following error when you try to create a model with a constructor.

`ArgumentCountError: Too few arguments to function App\Models\Product::__construct(), 0 passed in /Users/me/Github/example-app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php on line 67 and exactly 1 expected`

### Steps To Reproduce

1. Create a new Model
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public $name;

    public function __construct($name)
    {
        parent::__construct();

        $this->name = $name;
    }
}
```

2. Instantiate it either in an endpoint or test file

`ProductController.php`
```php
<?php

namespace Tests\Unit;

use App\Models\Product;
use PHPUnit\Framework\TestCase;

class ProductTest extends TestCase
{
    /** @test */
    public function product_constructor_assigns_values_correctly()
    {
        $name = "Laptop";

        $product = new Product($name);

        $this->assertEquals($name, $product->name, "The name should be initialized correctly.");
    }
}
```

or

`ProductTest.php`
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    public function store(Request $request)
    {

        $product = new Product("foo");
        
        $product->save();

        return response()->json($product, Response::HTTP_CREATED);
    }
}
```

3. Execute the code 
```
./vendor/bin/phpunit --filter ProductTest
```
or (whatever way you prefer)
`curl http://127.0.0.1:8000/product | grep "Too few arguments to function"`

This was caused by https://github.com/laravel/framework/pull/49843, reverting the content of HasEvents.php to the state before the change works fine.

Experienced this while trying to upgrade from 9 -> 10.
