### PR TITLE
[6.x] Fix report method for ViewException

### LINKED ISSUE #36108: ViewException does not provide dependencies to the wrapped report method
- Laravel Version: 6.20.15 / 8.25.0 / 9.x (8076d8628f6ca3c9f336bc5457ae00a4c13dbd74)
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

The `ViewException` class introduced in https://github.com/laravel/framework/pull/36032 does not pass dependencies to the wrapped exception's `report` method. This causes a fatal error when an exception thrown in a view has a dependency

See the docs:

>  You may type-hint any required dependencies of the report method and they will automatically be injected into the method by Laravel's service container.
> https://laravel.com/docs/8.x/errors#renderable-exceptions

### Steps To Reproduce:

1. Create a new Laravel project
1. Remove Ignition & Collision (`composer remove facade/ignition nunomaduro/collision`) [6.x & 8.x only]
1. Create a custom exception class with a `report` method that requires dependencies, e.g.:
    ```php
    namespace App\Exceptions;

    class MyException extends \Exception
    {
        public function report(\Illuminate\Contracts\Auth\Guard $guard)
        {
            return false;
        }
    }
    ```
1. Throw an instance of this exception in a view
1. An `ArgumentCountError` is thrown:
    > Too few arguments to function App\Exceptions\MyException::report()

### LINKED ISSUE #36109: ViewExceptions will never be logged
- Laravel Version: 6.20.15 / 8.25.0 / 9.x (8076d8628f6ca3c9f336bc5457ae00a4c13dbd74)
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

The `ViewException` class introduced in https://github.com/laravel/framework/pull/36032 will never be logged because its `report` method always returns `null`. Any return value other than `false` will suppress logging, so no exceptions thrown in views will be logged

`ViewException` also doesn't return the wrapped exception's `report` value, so wrapped exceptions cannot change the return value

### Steps To Reproduce:

1. Create a new Laravel project
1. Remove Ignition & Collision (`composer remove facade/ignition nunomaduro/collision`) [6.x & 8.x only]
1. Throw an exception in a view
1. The log file is empty

### PR DESCRIPTION
**Pull request by driesvints**
I didn't take into account that the `report` method can resolve dependencies from the container. This PR fixes just that.

It also fixes the incorrect return types now present on the `report` method's DocBlock return annotations.

Fixes https://github.com/laravel/framework/issues/36108 https://github.com/laravel/framework/issues/36109

### CODE REVIEW

File: src/Illuminate/View/ViewException.php [hunk 1]
```diff
@@ -3,20 +3,22 @@
...
      */
     public function report()
     {
         $exception = $this->getPrevious();
 
-        if ($exception && method_exists($exception, 'report')) {
-            $exception->report();
+        if (Reflector::isCallable($reportCallable = [$exception, 'report'])) {
+            return Container::getInstance()->call($reportCallable);
         }
```
Comment (imjoehaines) [inline src/Illuminate/View/ViewException.php:22]: I think this also needs to return `false` if the previous exception doesn't have a `report` method. Otherwise exceptions that don't implement `report` will still not be logged:

```suggestion
        if (Reflector::isCallable($reportCallable = [$exception, 'report'])) {
            return Container::getInstance()->call($reportCallable);
        }

        return false
```

Comment (driesvints) [reply src/Illuminate/View/ViewException.php:22]: Good catch 👍
