### ISSUE TITLE
Too few arguments to function EncryptCookies::decryptCookie()

### ISSUE THREAD

**Issue by olixr** [laravel/framework#26854]
- Laravel Version: 5.6.*
- PHP Version: 7.2
- Database Driver & Version: Mysql 
- Session/Cache: memcached
- Ubuntu 

### Description:
Doing some recent work in a project I started getting this bug: **Too few arguments to function Illuminate\Cookie\Middleware\EncryptCookies::decryptCookie(), 1 passed in /app/Http/Middleware/EncryptCookies.php on line 26 and exactly 2 expected.**

The changes made were minimal and cosmetic only, nothing related to middleware/cookies. I reverted the recent changes by going back before the last pull, reset the cache, restarted the server, tried to restart memcahce. This error still persists after reverting back changes to before the error was occurring. I am confused to the cause still and have not found any related bugs. 

I also looked into the cookie serialization due to the upgrade guide of 5.6.3, I am unsure this is related to that as well.

The issue does not occur locally (which uses valet) leading me to think some config or session setting is hanging up?

### Steps To Reproduce:
Trying to visit any page leads to this result:

![screen shot 2018-12-14 at 12 27 46 pm](https://user-images.githubusercontent.com/14366121/50025593-afe04080-ffab-11e8-8e93-2351c01e745d.png)

**Comment by staudenmeir** [comment]
Please post your `EncryptCookies` middleware. Does it work with Laravel 5.6.29?

**Comment by staudenmeir** [comment]
Laravel 5.6.30 changed the signature of `decryptCookie()`. Did you adjust the call(s) in your middleware?

**Comment by driesvints** [comment]
Heya, unfortunately we don't support this version anymore. Please try to upgrade or try the suggestions posted above.

@staudenmeir @sisve thanks for helping out guys 👍

**Comment by olixr** [comment]
After messing with the composer.lock file and upgrading to 5.6.3 I was able to resolve this issue. Thank you @staudenmeir and @sisve for the help.

We are planning to update to 5.7 here soon as well.
