### ISSUE TITLE
[5.5.1] Eloquent relation create fail.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#20948]
- Laravel Version: 5.5.1
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7.18

### Description:
After upgrade framework, I got a problem with this code.

```
    $message = $subject->Message()->create(array_add($request->all(), 'user_id', \Auth::id()));
```

It work in laravel 5.4. I seen in upgrade guild say any thing about this. But I don't get it.

This is error. I work with axios.
```
message : Type error: Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /Users/ThunderBirdsX3/Desktop/Workspace/mcchat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 525 and exactly 2 expected
file : /Users/ThunderBirdsX3/Desktop/Workspace/mcchat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php
line : 517
```
### Steps To Reproduce:

Subject Model.
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
  protected $fillable = [
    'client_id', 'title'
  ];

  public function Client()
  {
    return $this->belongsTo(Client::class);
  }

  public function User()
  {
    return $this->belongsToMany(User::class, 'subscribes');
  }

  public function Message()
  {
    return $this->hasMany(Message::class);
  }
}
```

Message Model.
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
  protected $fillable = [
    'user_id', 'type', 'data'
  ];

  /**
   * All of the relationships to be touched.
   *
   * @var array
   */
  protected $touches = ['Subject'];

  const UPDATED_AT = null;

  public function Subject()
  {
    return $this->belongsTo(Subject::class);
  }

  public function User()
  {
    return $this->belongsTo(User::class);
  }

  public function UnreadUser()
  {
    return $this->belongsToMany(User::class, 'unread_users');
  }

  public function UnreadClient()
  {
    return $this->belongsToMany(Client::class, 'unread_clients');
  }
}
```

MessageController.
```
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Events\UserSendMessage;

use App\Subject;
use App\Message;

class MessageController extends Controller
{
  ...
  public function store(Request $request, Subject $subject)
  {
    $message = $subject->Message()->create(array_add($request->all(), 'user_id', \Auth::id()));

    $message->UnreadClient()->attach($subject->client_id);

    event(new UserSendMessage($message));

    return $message;
  }
  ...
}
```
With this route.
```
  Route::resource('/subjects/{subject}/messages', 'MessageController');
```

**Comment by themsaid** [comment]
We don't know what's in your `$request->all()`, please submit how to recreate without vague values.

**Comment by ThunderBirdsX3** [comment]
@themsaid If I use `$request->all()` it will pick only data with in `$fillable` right?

`$request->all()` have data like below. 
```
[
  'type' => 'text',
  'data' => 'Some text',
]
```

**Comment by themsaid** [comment]
I'm unable to replicate your issue, 

```
$subject->Message()->create([
        'type' => 'text',
        'data' => 'Some text',
    ]);
```

Works fine for me, please debug your code and find what's the result of this `array_add($request->all(), 'user_id', \Auth::id())` block.

**Comment by ThunderBirdsX3** [comment]
`Message` want 'user_id' one.

**Comment by ThunderBirdsX3** [comment]
@themsaid  I already try this.
```
$subject->Message()->create([
  'type' => 'text',
  'data' => 'Some text',
  'user_id' => \Auth::id()
]);
```

But I still got same error.

**Comment by themsaid** [comment]
Still don't seem to be able to replicate, please create a test repo with a fresh laravel installation with the issue replicated, maybe something in your project configuration is causing the issue so better try to replicate it in a fresh installation.

**Comment by ThunderBirdsX3** [comment]
@themsaid this is a [link](https://drive.google.com/open?id=0B25sV78j5VVBUmZsRmpxT3JpOFU). This code is fresh laravel installation, Then copy used function across.

**Comment by themsaid** [comment]
@ThunderBirdsX3 this is your project, I can't browser your project to find what's wrong with it :)

Please explain on a fresh laravel installation how to replicate your issue as I can't replicate it using a Subject and Message models with a hasMany relationship, passing the same attributes as you do.

Create a fresh laravel project and try to replicate the issue using the minimum amount of code and bing me to open the issue.

**Comment by ThunderBirdsX3** [comment]
@themsaid I try to play around about it and I think i found some thing.

About `const UPDATED_AT = null;` in Message Model. I try to commend this code and add `updated_at` to table `messages`. The result is I didn't get any error. Then I try to uncomment and try again and I got an errors. I try one more time with `const UPDATED_AT = 'created_at';` and it work. Could you look over this, Please.

**Comment by ThunderBirdsX3** [comment]
@themsaid How about this?

**Comment by oknixus** [comment]
Yes. When use `const UPDATED_AT=null;` will got this error. Bug Why ?
