### ISSUE TITLE
ViewException does not provide dependencies to the wrapped report method

### ISSUE THREAD

**Issue by imjoehaines** [laravel/framework#36108]
- Laravel Version: 6.20.15 / 8.25.0 / 9.x (8076d8628f6ca3c9f336bc5457ae00a4c13dbd74)
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:

The `ViewException` class introduced in https://github.com/laravel/framework/pull/36032 does not pass dependencies to the wrapped exception's `report` method. This causes a fatal error when an exception thrown in a view has a dependency

See the docs:

>  You may type-hint any required dependencies of the report method and they will automatically be injected into the method by Laravel's service container.
> https://laravel.com/docs/8.x/errors#renderable-exceptions

### Steps To Reproduce:

1. Create a new Laravel project
1. Remove Ignition & Collision (`composer remove facade/ignition nunomaduro/collision`) [6.x & 8.x only]
1. Create a custom exception class with a `report` method that requires dependencies, e.g.:
    ```php
    namespace App\Exceptions;

    class MyException extends \Exception
    {
        public function report(\Illuminate\Contracts\Auth\Guard $guard)
        {
            return false;
        }
    }
    ```
1. Throw an instance of this exception in a view
1. An `ArgumentCountError` is thrown:
    > Too few arguments to function App\Exceptions\MyException::report()

**Comment by driesvints** [comment]
Urgh, I didn't take that into account. I'll get that fixed 👍

**Comment by driesvints** [comment]
@imjoehaines can you try modifying the `ViewException` class to the following below and see if that works?

```php
<?php

namespace Illuminate\View;

use ErrorException;
use Illuminate\Container\Container;
use Illuminate\Support\Reflector;

class ViewException extends ErrorException
{
    /**
     * Report the exception.
     *
     * @return void
     */
    public function report()
    {
        $exception = $this->getPrevious();

        if (Reflector::isCallable($reportCallable = [$exception, 'report'])) {
            Container::getInstance()->call($reportCallable);
        }
    }

    /**
     * Render the exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function render($request)
    {
        $exception = $this->getPrevious();

        if ($exception && method_exists($exception, 'render')) {
            return $exception->render($request);
        }
    }
}
```

**Comment by imjoehaines** [comment]
> @imjoehaines can you try modifying the `ViewException` class to the following below and see if that works?

Yeah, that works 🙂
