### PR TITLE
[11.x] Do not wipe database if it does not exists

### PR DESCRIPTION
**Pull request by driesvints**
If the `migrate:fresh` command is called while there isn't any database created yet, it'll fail when it tries to wipe the database. This PR fixes this by first checking if the migrations table exists and if not, immediately go to the migrate command by skipping the `db:wipe` command. This will invoke the `migrate` command flow and subsequently will reach the point where the command will ask the user to create the database. 

In combination with https://github.com/laravel/framework/pull/50836 this will offer a more seamless experience for people attempting to install Jetstream through the Laravel installer and choosing to not create the database.

Screenshot 2024-03-29 at 12 23 26

### CODE REVIEW

**Review by nunomaduro — APPROVED** [review]

**Comment by streamingsystems** [comment]
Hi All,

I use Laravel Lumen and have my own fork that upgraded to the Laravel 11 Framework (the standard repo goes up to 10). I believe that Lumen is not officially supported but I am sure there are a lot of folks out there (like me) that still use it. 

Anyhow, when I upgraded today to 11.2.0 it blew me up: 

In FreshCommand.php line 45:
                                                                                                                                                                 
  Too few arguments to function Illuminate\Database\Console\Migrations\FreshCommand::__construct(), 0 passed in /home/ss/application-origin/vendor/laravel/lume  
  n-framework/src/Console/ConsoleServiceProvider.php on line 211 and exactly 1 expected         

It looks like this fix changed the constructor and instead of using the Command base class constructor (which was an empty constructor) it now requires a Migrator.

I had to change this: 

protected function registerMigrateFreshCommand()
    {
        $this->app->singleton('command.migrate.fresh', function () {
            return new MigrateFreshCommand;
        });
    }                                                         
             
to this: 

protected function registerMigrateFreshCommand()
    {
        $this->app->singleton('command.migrate.fresh', function ($app) {
            return new MigrateFreshCommand($app['migrator']);
        });
    }              

And it fixed it. 

I was more writing this to let you know that other folks that have Laravel Lumen that is using the Laravel 11 framework it will blow them up. Not sure if you can make that constructor backwards compatible. 

Thanks!

-Rob
