### ISSUE TITLE
ThrottleRequest breaks when trying to access undefined getAuthIdentifier method

### ISSUE THREAD

**Issue by chaoszcat** [laravel/framework#21118]
- Laravel Version: 5.5.3
- PHP Version: 7.1
- Database Driver & Version: -

### Description:
If `User` Model do not implement the `Authenticatable` interface, the `ThrottleRequests` breaks at `resolveRequestSignature` when it tries to access undefined method `getAuthIdentifier()` from the `$user` property.

In our system, we uses `Account` to authenticate users, while `User` do not inherit the `Authenticatable` interface. It's working fine from 5.0 to 5.4, and it breaks when I upgrade to 5.5.3.

### Suggestion:
Change the `resolveRequestSignature` in `\Illuminate\Routing\Middleware\ThrottleRequests` to cross check if it has implemented `Authenticatable` or not:

```
protected function resolveRequestSignature($request)
{
    if (($user = $request->user()) && $user instanceof \Illuminate\Contracts\Auth\Authenticatable) {
        return sha1($user->getAuthIdentifier());
    }

    if ($route = $request->route()) {
        return sha1($route->getDomain().'|'.$request->ip());
    }

    throw new RuntimeException(
        'Unable to generate the request signature. Route unavailable.'
    );
}
```

**Comment by themsaid** [comment]
Will update the docs for this breaking change, but you should implement this interface in your Account model as per the docs: https://laravel.com/docs/5.5/authentication#the-authenticatable-contract

**Comment by chaoszcat** [comment]
You are expecting developer to implement authenticatable when using ThrottleRequest? For our use case is that we have two type of users that one implements authenticatable (with username/password, global account) that translates to local user which does not implement it. If this is a won't fix then my only solution now is to extend ThrottleRequest and rewrite this method then. Thanks!

**Comment by themsaid** [comment]
Ok will open a PR addressing that, you have a point. Thanks :)
