### ISSUE TITLE
Model has no changes after update, if listeners are on redis queue.

### ISSUE THREAD

**Issue by Miljan9602** [laravel/framework#29885]
- Laravel Version: 6.0.1
- PHP Version: 7.3.6
- Database Driver & Version: PostgreSQL 11.3 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit

### Description:
I have event which eloquent model fire when it is updated.
When listener implements ShouldQueue, updated model from event does not receive changes.
When listener does not implement ShouldQueue, updated model from event receive changes.

Redis is used as queue for listeners.

### Steps To Reproduce:
I will send the link of the repository where i wrote code that caused bug. There are two commits, first one is initial and the second one is the code that caused this error.

https://github.com/Miljan9602/LaravelUpdateBug

This is my log storage:

This one is the log without changes, when using listener with the queue.

[2019-09-05 22:02:35] local.ERROR: Model updated {"current_user":{"App\\User":{"id":1,"name":"Ms. Rosanna Hudson MD","email":"pl4J3w2bHtfRO5XO","email_verified_at":"2019-09-05 22:02:35","created_at":"2019-09-05 22:02:35","updated_at":"2019-09-05 22:02:35"}},"update_changes":[]} 

This one is the log with changes, when using listener without queue.
[2019-09-05 22:03:05] local.ERROR: Model updated {"current_user":{"App\\User":{"name":"Wilmer Fritsch","email":"VdwbeQa0OFYaqYhl","email_verified_at":"2019-09-05 22:03:05","updated_at":"2019-09-05 22:03:05","created_at":"2019-09-05 22:03:05","id":2}},"update_changes":{"email":"VdwbeQa0OFYaqYhl"}}

**Comment by driesvints** [comment]
Which redis driver are you using? Did you do all the necessary changes from the upgrade guide?

**Comment by Miljan9602** [comment]
@driesvints This is also does not work on Laravel: 5.8.33. Project is fresh installed, so it is not updated from older version to the new version.

Redis client is set to predis. What more info can provide? 

I provided also project link on github.

**Comment by devcircus** [comment]
Just cloned your repo and redis works as expected. You have a lot of redis configuration customization. I stripped the customization out and replaced with the default configuration and everything works fine. There's an issue in your configuration somewhere. 

In a bit, I'll put your code back in and see if I can help track down the issue.

**Comment by devcircus** [comment]
Just tried using your code as-is and it works as expected too, so your configuration seems to be ok. It will be difficult to help debug when the code works on our end.

**Comment by driesvints** [comment]
Going to close this then as a support question. Feel free to use one of the below channels or continue your discussion here.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
